### ISSUE TITLE
Compiling on windows

### ISSUE THREAD

**Issue by jrbrodie77** [rmaugusto/qblade#1]
Any chance you're compiling for windows? I'm trying to compile the original Qblade and running into trouble. (I'm actually in the process of building an Ubuntu VM to see if that helps).  Any tips for compilation would help.

**Comment by rmaugusto** [comment]
My branch is working fine on Windows but not on Linux.
Please try official repository in [https://sourceforge.net/projects/qblade/](https://sourceforge.net/projects/qblade/)
